# Application
spring.application.name=api-gateway
server.port=${SERVER_PORT:8765}

# Spring Cloud Gateway
spring.cloud.gateway.mvc.enabled=true

# Route : Auth Service
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth-service/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1


# Optional Dynamic Discovery Routing
# spring.cloud.gateway.discovery.locator.enabled=true
# spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Actuator
#http://localhost:8765/actuator/mappings - For check mappings
management.endpoints.web.exposure.include=health,info,mappings
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true

#Application Info
info.app.name=${spring.application.name}
info.app.description=API Gateway Service
info.app.version=@project.version@

# Logging
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.web=WARN